
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AskandLearn' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for AskandLearn
  pod 'Parse'
  pod 'DateTools'
  pod 'MBProgressHUD'
  pod 'AFNetworking','2.0'
  pod 'BDBOAuth1Manager’
  pod 'FBSDKLoginKit'
  
  target 'AskandLearnTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'AskandLearnUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
end
