platform :ios, '11.0'

target 'AskandLearn' do
  
  # Pods for AskandLearn
  pod 'Parse'
  pod 'BDBOAuth1Manager'
  pod 'DateTools'
  pod 'MBProgressHUD'
  pod 'AFNetworking'
end

  target 'AskandLearnTests' do
    inherit! :search_paths
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
  end
end
